language: python
python:
  - "2.7"
services: mysql
env:
  - DJANGO=1.10 
before_install:
   - cd underTheaterWS/
install:
  - pip install -r requirements.txt
  
before_script:
  - mysql -e 'create database travisci;'
  - cp  underTheaterWS/travis_settings.py  underTheaterWS/my_local_settings.py
  - python manage.py migrate
script:
  - python manage.py test underTheaterApp.tests
