language: python
python:
  - "2.7"
services: mysql
env:
  - DJANGO=1.10 DJANGO_SETTINGS_MODULE="underTheaterWS.travis_settings"
before_install:
   - cd underTheaterWS/
install:
  - pip install -r requirements.txt
  
before_script:
  - mysql -e 'create database travisci;'
  - cd underTheaterWS/
  - python manage.py migrate
script:
  - python manage.py test underTheaterApp
