# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 21:28
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.IntegerField(verbose_name='Numero de telefono')),
                ('facebook', models.CharField(blank=True, max_length=128, verbose_name='usuario en Facebook')),
                ('share_address', models.BooleanField(default=True, help_text='Compartir la direccion', verbose_name='Compartir direccion')),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_show', models.DateTimeField(auto_now=True, verbose_name='dia y horario del show')),
            ],
        ),
        migrations.CreateModel(
            name='PlayPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlayTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(max_length=200)),
                ('synopsis', models.TextField(max_length=500, verbose_name='Sinopsis de la obra')),
                ('picture', models.ImageField(upload_to='playImages')),
                ('actors', models.ManyToManyField(to='underTheaterApp.Actor', verbose_name='actors')),
                ('datetime_show', models.ManyToManyField(to='underTheaterApp.DateTimeShow', verbose_name='datetime_show')),
                ('price', models.ManyToManyField(related_name='play_price', to='underTheaterApp.PlayPrice', verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(verbose_name='cantidad de asientos libres')),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('name', models.CharField(max_length=200, unique=True)),
                ('review', models.TextField(max_length=500, verbose_name='rese\xf1a del teatro')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='theater_contact', serialize=False, to='underTheaterApp.Contact', verbose_name='contacto')),
            ],
        ),
        migrations.AddField(
            model_name='playtheater',
            name='room_theater',
            field=models.ManyToManyField(related_name='room', to='underTheaterApp.TheaterRoom', verbose_name='sala de la obra'),
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AddField(
            model_name='theaterroom',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_room', to='underTheaterApp.Theater', verbose_name='theater'),
        ),
        migrations.AddField(
            model_name='playtheater',
            name='theater',
            field=models.ManyToManyField(related_name='play_theater', to='underTheaterApp.Theater', verbose_name='theater'),
        ),
    ]
