# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='static/logo.png', upload_to='static/profileImages'),
        ),
    ]
