# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateshow',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_date_show', to='underTheaterApp.PlayTheater', verbose_name='play'),
        ),
        migrations.AlterField(
            model_name='playprice',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_price', to='underTheaterApp.PlayTheater', verbose_name='play'),
        ),
        migrations.AlterField(
            model_name='playtheater',
            name='actors',
            field=models.ManyToManyField(to='underTheaterApp.Actor', verbose_name='actors'),
        ),
        migrations.AlterField(
            model_name='playtheater',
            name='theater',
            field=models.ManyToManyField(related_name='play_theater', to='underTheaterApp.Theater', verbose_name='theater'),
        ),
        migrations.AlterField(
            model_name='theaterroom',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_room', to='underTheaterApp.Theater', verbose_name='theater'),
        ),
    ]
