# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0002_auto_20160906_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_contact', to='address.Address', verbose_name='address'),
        ),
    ]
