# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0002_auto_20161005_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketeable',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='undertheaterapp_ticket_related', to='underTheaterApp.Ticketeable', verbose_name='ticketeable'),
            preserve_default=False,
        ),
    ]
