# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0003_auto_20160907_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtheater',
            name='picture',
            field=models.ImageField(upload_to='static/playImages'),
        ),
    ]
