# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0003_auto_20161109_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('play_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='underTheaterApp.PlayTheater')),
                ('user_profile_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to='underTheaterApp.Profile')),
            ],
        ),
    ]
