# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0004_auto_20160908_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_show', models.DateTimeField(verbose_name='dia y horario de la funcion')),
                ('price', models.ManyToManyField(related_name='day_function_price', to='underTheaterApp.PlayPrice', verbose_name='price')),
                ('room_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_function_room', to='underTheaterApp.TheaterRoom', verbose_name='sala de la obra')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_function_theater', to='underTheaterApp.Theater', verbose_name='teatro')),
            ],
        ),
        migrations.RemoveField(
            model_name='playtheater',
            name='datetime_show',
        ),
        migrations.RemoveField(
            model_name='playtheater',
            name='price',
        ),
        migrations.RemoveField(
            model_name='playtheater',
            name='room_theater',
        ),
        migrations.RemoveField(
            model_name='playtheater',
            name='theater',
        ),
    ]
