# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-17 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0004_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('user_profile_rate', 'play_theater')]),
        ),
    ]
