# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import underTheaterApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0005_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayfunction',
            name='play_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayfunction_related', to='underTheaterApp.PlayTheater', verbose_name='obra'),
        ),
        migrations.AlterField(
            model_name='playtheater',
            name='synopsis',
            field=models.TextField(max_length=1000, validators=[underTheaterApp.validators.min_words_validator], verbose_name='Sinopsis de la obra'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketeable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_related', to='underTheaterApp.Ticketeable', verbose_name='ticketeable'),
        ),
    ]
