# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 01:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import underTheaterApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0005_auto_20161117_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000, validators=[underTheaterApp.validators.min_words_validator], verbose_name='Descripcion de la clase')),
                ('picture', models.FileField(upload_to='static/class_theater')),
                ('with_interview', models.BooleanField(default=True, verbose_name='Con entrevista previa')),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(15)])),
                ('datetime_function', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='underTheaterApp.DateTimeFunction', verbose_name='dia y horario de la clase')),
                ('room_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='underTheaterApp.TheaterRoom', verbose_name='sala de la clase')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to='underTheaterApp.Theater', verbose_name='teatro')),
            ],
        ),
    ]
