# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0006_playtheater_day_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playtheater',
            name='day_function',
        ),
        migrations.AddField(
            model_name='dayfunction',
            name='play_theater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='underTheaterApp.PlayTheater', verbose_name='obra'),
            preserve_default=False,
        ),
    ]
