# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-23 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0006_auto_20161014_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketeable',
            name='topic',
            field=models.CharField(max_length=250),
        ),
    ]
