# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('underTheaterApp', '0007_auto_20161124_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='playtheater',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='due\xf1o de la publicacion'),
            preserve_default=False,
        ),
    ]
