# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0007_auto_20160926_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playtheater',
            name='picture',
            field=models.FileField(upload_to='static/playImages'),
        ),
    ]
