# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('underTheaterApp', '0008_auto_20160927_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='dayfunction',
            name='price',
        ),
        migrations.DeleteModel(
            name='PlayPrice',
        ),
        migrations.AddField(
            model_name='ticket',
            name='day_function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_function_ticket', to='underTheaterApp.DayFunction', verbose_name='day_function'),
        ),
    ]
